language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
env:
  - DJANGO_VERSION=1.7.*
  - DJANGO_VERSION=1.8.*
  - DJANGO_VERSION=1.9.*
matrix:
  exclude:
    - python: 3.5
      env: DJANGO_VERSION=1.7.*
install:
  - pip install -U pip wheel
  - pip install django==$DJANGO_VERSION
  - pip install -r test-requires.txt
before_script: flake8 django_redshift_backend
script:
  - py.test
  - python setup.py sdist bdist_wheel
  - python setup.py check -s -r
