language: python
sudo: false
python:
  - "2.7"
install:
  - pip install -U pip
  - pip install wheel docutils flake8
before_script: flake8 django_redshift_backend
script:
  - python setup.py sdist bdist_wheel
  - python setup.py check -s -r
