language: python
sudo: false
cache: pip
matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: DJANGO_VERSION=1.11.*
  - python: 3.5
    env: DJANGO_VERSION=1.11.*
  - python: 3.6
    env: DJANGO_VERSION=1.11.*
  - python: 3.5
    env: DJANGO_VERSION=2.0.*
  - python: 3.6
    env: DJANGO_VERSION=2.0.*
install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install django==$DJANGO_VERSION
  - pip install -U -r test-requires.txt
before_script: flake8 django_redshift_backend
script:
  - py.test
  - python setup.py sdist bdist_wheel
  - python setup.py check -s -r
