language: python
sudo: false
cache: pip
matrix:
  fast_finish: true
  include:
  - env: TOX_ENV=py27-dj111
    python: 2.7
  - env: TOX_ENV=py35-dj111
    python: 3.5
  - env: TOX_ENV=py36-dj111
    python: 3.6
  - env: TOX_ENV=py35-dj20
    python: 3.5
  - env: TOX_ENV=py36-dj20
    python: 3.6
  - env: TOX_ENV=flake8
    python: 3.6
  - env: TOX_ENV=readme
    python: 3.6
install:
- pip install -U pip setuptools tox
script:
- tox -e "${TOX_ENV}"
